// Hand-written rather than generated by @astrojs/sitemap, which always emits a
// sitemap index plus numbered chunks even when there is a single chunk. At 3730
// URLs and ~440 KB we sit at 7 % of the protocol's 50 000 URL / 50 MB ceiling,
// so the index level added a hop and a second filename for nothing. One flat
// file under the conventional name is what crawlers and humans both expect.
//
// Splitting only becomes necessary if the publication threshold ever drops far
// enough to clear 50 000 pages — the 20-sale threshold would yield 8334.

import { allCommunes } from '../lib/communes.js'
import { departments } from '../lib/departments.js'
import { pairPath, pairs } from '../lib/pairs.js'
import { roomHubPath, roomHubs, roomPagePath, roomPages } from '../lib/rooms.js'
import { LAST_MODIFIED } from '../lib/dataset.js'

// Everything is regenerated at once, so the whole site shares one lastmod —
// without it crawlers have no signal that thousands of pages changed together
// when the dataset is refreshed twice a year.
//
// It is the later of the DVF release and the last deliberate content change,
// never the build date: see LAST_MODIFIED in lib/dataset.js for why.
const lastmod = LAST_MODIFIED

// Read off the filesystem rather than listed by hand. Four ranking pages were
// added in a single afternoon, and nothing but memory stood between them and a
// sitemap that never mentioned them.
//
// Only `.astro` files are picked up, so the endpoints next to them — the search
// index, llms.txt, this file — stay out by construction: they are wire formats
// and crawler files, not pages. Dynamic routes are excluded by their brackets;
// they are enumerated from the data below. That leaves the 404 to name.
const EXCLUDED = new Set(['404'])

const staticPaths = Object.keys(import.meta.glob('./*.astro'))
  .map((file) => file.slice(2, -'.astro'.length))
  .filter((name) => !name.includes('[') && !EXCLUDED.has(name))
  .map((name) => (name === 'index' ? '/' : `/${name}`))
  .sort()

export function GET({ site }) {
  const paths = [
    ...staticPaths,
    ...allCommunes.map((commune) => `/prix-immobilier-${commune.slug}`),
    ...departments.map((department) => `/prix-immobilier-departement-${department.slug}`),
    // The hubs are dynamic routes, so the glob above skips them by their
    // brackets the same way it skips the commune pages: both are listed here.
    ...roomHubs.map((rooms) => roomHubPath(rooms)),
    ...roomPages.map(({ commune, rooms }) => roomPagePath(commune, rooms)),
    // Only the canonical order of each pair. The reverse spelling exists as a
    // 301 in public/_redirects and has no business in a sitemap.
    ...pairs.map(({ a, b }) => pairPath(a, b)),
  ]

  // No XML escaping: every path is built from slugs, which are already reduced
  // to [a-z0-9-] upstream. Anything else here would be a slugification bug
  // worth surfacing rather than silently encoding.
  const urls = paths
    .map((path) => `<url><loc>${new URL(path, site).href}</loc><lastmod>${lastmod}</lastmod></url>`)
    .join('')

  const xml = `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`

  return new Response(xml, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  })
}
